### ISSUE TITLE
Added OAUTH flow to support Strava authentication. Still need to persist the athletes data and refreshAccessToken. Almost done

### ISSUE THREAD

**Issue by eaudet** [eaudet/trainingbot#26]

**Comment by eaudet** [comment]
Todo: com.jarics.trainbot.controllers.TrainingBotController#auth

- [ ] persistence athlete + accessToken (create nitrite entity)
- [ ] need to refreshtoken everytime we use the strava api

**Comment by eaudet** [comment]
com.jarics.trainbot.StravaServiceTests#testGetActivities 

Seems like I have an authorization issue:

`Exception when calling ActivitiesApi#getLoggedInAthleteActivities
io.swagger.client.ApiException: Unauthorized
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:926)
	at io.swagger.client.ApiClient.execute(ApiClient.java:842)
	at io.swagger.client.api.ActivitiesApi.getActivityByIdWithHttpInfo(ActivitiesApi.java:348)
	at io.swagger.client.api.ActivitiesApi.getActivityById(ActivitiesApi.java:333)`

**Comment by eaudet** [comment]
The loop works fine. The only problem that once the strava is calling back TrainingBot /athlete, it loads the page and we loose the login since it is in the store. We need to store the login in a local storage or cookie...

**Comment by eaudet** [comment]
Persist the hole store in local storage...That way when we return to trainBot avec linking with strava, we will still be logged in.
https://flaviocopes.com/vuex-persist-localstorage/

**Comment by eaudet** [comment]
We will notify that for security purposes, after linking with Strava, user will need to login again.

**Comment by eaudet** [comment]
- [ ] Need to persist strava client id in athlete entity
- [ ] Need to add controller parameter to stravaService (stravaClientId) and remove it from properties.
- [ ] Need to add stravaClientId in Athletes form like any other attributes.

**Comment by eaudet** [comment]
![image](https://user-images.githubusercontent.com/288285/57185595-8eb9b700-6e9c-11e9-855b-c7602d92b9d9.png)

**Comment by eaudet** [comment]
client_id and client_secret are variables that belong to the application (not the athlete).
